### ISSUE TITLE
Limerick License for your Limerick OS

### ISSUE THREAD

**Issue by alexgenaud** [nakotami/limerick#1]
(c) 2022 Nako Tami

    Permission is granted hereby,
    to copy, share, use, modify,
       for purposes any,
       free or for penny,
    provided these rhymes multiply.

    This work "as is" I provide,
    no warranty express or implied,
       for, no purpose fit,
       'tis unmerchantable shit.
    Liability for damages denied.

**Comment by nakotami** [comment]
Haha, thank you for this licence! I'll add it right now.
